### PR TITLE
Fix after fairseq

### PR DESCRIPTION
**Pull request by G-Thor**
Did some fixes, particularly in voice/festival/clunits/all.desc to make the recipe work with the fairseq g2p.
Also cleaned up the phoneme descriptions and definitions with the correct names for places of articulation.

### CODE REVIEW

**Comment by judyfong** [comment]
Why DID it sound so awful after adding fairseq?

**Comment by G-Thor** [comment]
The phonemes that were swapped out couldn't be used by festival because their definitions were missing. i.e. they had to be defined in two places, and one of these places was missing.

**Comment by G-Thor** [comment]
One part of the training pipeline (I don't recall which) threw a bunch of errors for unknown phones at least.

**Comment by judyfong** [comment]
ah, in the all.desc file

**Review by judyfong — APPROVED** [review]
It sounds great now. Even the Halló pronunciation has improved.

**Pull request merged**
